version: "3"

services:

  # RabbitMQ
  rabbitmq-dev:
    build: ./rabbitmq
    image: "rabbitmq-prototype-server"
    ports:
      - "5672:5672"
      - "15672:15672"

  # PostgreSQL
  postgresql-dev:
    build: ./postgresql
    image: "postgresql-prototype-server"
    ports:
      - "5432:5432"
